---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=cbc5639a12a35af201780d1b09499e6c1d2f5081
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=cbc5639a12a35af201780d1b09499e6c1d2f5081
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=cbc5639a12a35af201780d1b09499e6c1d2f5081

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/cbc5639a12a35af201780d1b09499e6c1d2f5081/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/cbc5639a12a35af201780d1b09499e6c1d2f5081/examples/features/vl3-basic/nse-patch.yaml
