---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=17bf4171f764f37135945425e7ee8e5e0ef9b06e
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=17bf4171f764f37135945425e7ee8e5e0ef9b06e
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=17bf4171f764f37135945425e7ee8e5e0ef9b06e

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/17bf4171f764f37135945425e7ee8e5e0ef9b06e/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/17bf4171f764f37135945425e7ee8e5e0ef9b06e/examples/features/vl3-basic/nse-patch.yaml
