---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=54be5919503470fa8b3370bcc5e7f17dbc7df6b2
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=54be5919503470fa8b3370bcc5e7f17dbc7df6b2
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=54be5919503470fa8b3370bcc5e7f17dbc7df6b2

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/54be5919503470fa8b3370bcc5e7f17dbc7df6b2/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/54be5919503470fa8b3370bcc5e7f17dbc7df6b2/examples/features/vl3-basic/nse-patch.yaml
