---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/54be5919503470fa8b3370bcc5e7f17dbc7df6b2/examples/features/vl3-scale-from-zero/autoscale-netsvc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/54be5919503470fa8b3370bcc5e7f17dbc7df6b2/examples/features/vl3-scale-from-zero/vl3-netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=54be5919503470fa8b3370bcc5e7f17dbc7df6b2
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=54be5919503470fa8b3370bcc5e7f17dbc7df6b2
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=54be5919503470fa8b3370bcc5e7f17dbc7df6b2

patchesStrategicMerge:
- nsc-patch.yaml
- supplier-patch.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/54be5919503470fa8b3370bcc5e7f17dbc7df6b2/examples/features/vl3-scale-from-zero/pod-template.yaml
